
export  const PHONE_NUMBER_SUCCESS ="PHONE_NUMBER_SUCCESS";
export const PHONE_NUMBER_FAILURE = "PHONE_NUMBER_FAILURE";
export const OTP_SUCCESS = "OTP_SUCCESS";
export const OTP_FAILURE = "OTP_FAILURE";
export const AADHAR_NUMBER_SUCCESS = "AADHAR_NUMBER_SUCCESS";
export const AADHAR_NUMBER_FAILURE = "AADHAR_NUMBER_FAILURE";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAILURE = "PROFILE_FAILURE";
export const USERSUGGEST = "USERSUGGEST";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";